kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cross-namespace-access
subjects:
- kind: ServiceAccount
  name: default-full-access-mounted
  namespace: fiw35684
roleRef:
  kind: Role
  name: r-k8s-p49-beamline
  apiGroup: rbac.authorization.k8s.io
