on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements
      
      - name: Install helm plugins
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git --version 2.2.1
        
      - name: Run tox
        run: tox -e ${{ inputs.tox }}
